"""Chapter 12: Multi-Level Memory — Four-Tier Agent Memory Architecture.

Teaches:
- Why a single memory store is insufficient for long-lived agents
- The four-tier cognitive memory model adapted for AI agents:
    Working Memory   → current conversation context (in-context, volatile)
    Episodic Memory  → past session summaries (out-of-context, persistent, searchable)
    Semantic Memory  → factual knowledge about the user and world (structured, persistent)
    Procedural Memory → how-to skills (referenced from ch10; pointer pattern shown here)
- How to build a unified MemoryManager facade that decides which tier to query
- How hermes-agent implements each tier in production

Run:
    python multi_level_memory.py
"""

from __future__ import annotations

import json
import os
import re
from collections import deque
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Tier 1 — Working Memory  (current conversation context)
# ---------------------------------------------------------------------------

class WorkingMemory:
    """Short-term, in-context sliding window of the current conversation.

    Backed by a ``collections.deque`` — the oldest messages are automatically
    evicted when the buffer reaches *max_messages*.  Nothing is persisted to
    disk; this memory disappears when the session ends.

    Cognitive analogy: the scratchpad a human keeps in mind while talking.
    """

    def __init__(self, max_messages: int = 20) -> None:
        self._buf: deque[dict[str, str]] = deque(maxlen=max_messages)

    def add(self, role: str, content: str) -> None:
        """Append a message to the working buffer."""
        self._buf.append({"role": role, "content": content})

    def get_messages(self) -> list[dict[str, str]]:
        """Return messages in chronological order (safe to pass to an LLM)."""
        return list(self._buf)

    def clear(self) -> None:
        """Discard all messages (start a new conversation turn)."""
        self._buf.clear()

    def summarise(self) -> str:
        """Produce a brief plain-text summary of the current context.

        In production (hermes-agent) this summary is generated by the LLM and
        then stored into Episodic Memory at session end.
        """
        if not self._buf:
            return "(空对话)"
        lines: list[str] = []
        for msg in self._buf:
            role_label = {"user": "用户", "assistant": "助手", "system": "系统"}.get(
                msg["role"], msg["role"]
            )
            snippet = msg["content"][:60].replace("\n", " ")
            lines.append(f"[{role_label}] {snippet}{'…' if len(msg['content']) > 60 else ''}")
        return "\n".join(lines)

    def __len__(self) -> int:
        return len(self._buf)


# ---------------------------------------------------------------------------
# Tier 2 — Episodic Memory  (past session summaries)
# ---------------------------------------------------------------------------

@dataclass
class Episode:
    """A summarised record of a past conversation session.

    Attributes:
        session_id:  Unique identifier for the session (ISO timestamp by default).
        summary:     LLM-generated (or rule-based) natural-language summary.
        keywords:    Topics discussed — used for keyword-based retrieval.
        started_at:  When the session began (ISO-8601).
        ended_at:    When the session ended / was summarised.
        message_count: Number of messages in the original session.
    """

    session_id: str
    summary: str
    keywords: list[str]
    started_at: str
    ended_at: str = field(default_factory=lambda: datetime.now().isoformat())
    message_count: int = 0

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "Episode":
        return cls(**data)


class EpisodicMemory:
    """Persistent store of past session summaries, searchable by keyword.

    Backed by a JSON file.  In hermes-agent this is a SQLite database with an
    FTS5 virtual table for full-text search — here we use keyword matching to
    stay dependency-free.

    Cognitive analogy: autobiographical memory — "last Tuesday we discussed X".
    """

    def __init__(self, filepath: str = ".episodic_memory.json") -> None:
        self.filepath = filepath
        self._episodes: list[Episode] = []
        self._load()

    # --- Persistence ---

    def _load(self) -> None:
        if os.path.exists(self.filepath):
            try:
                with open(self.filepath, "r", encoding="utf-8") as fh:
                    raw: list[dict] = json.load(fh)
                self._episodes = [Episode.from_dict(e) for e in raw]
            except (json.JSONDecodeError, OSError, TypeError):
                self._episodes = []

    def _save(self) -> None:
        with open(self.filepath, "w", encoding="utf-8") as fh:
            json.dump(
                [e.to_dict() for e in self._episodes],
                fh,
                indent=2,
                ensure_ascii=False,
            )

    # --- Write ---

    def store(self, episode: Episode) -> None:
        """Append a new episode and persist."""
        self._episodes.append(episode)
        self._save()

    # --- Read ---

    def get_recent(self, n: int = 5) -> list[Episode]:
        """Return the *n* most-recent episodes (newest last)."""
        return self._episodes[-n:]

    def search(self, query: str, top_k: int = 3) -> list[Episode]:
        """Return up to *top_k* episodes whose summary or keywords match *query*.

        Scoring:
          - Each keyword match in episode.keywords   → +2 pts
          - Each query word found in episode.summary → +1 pt
          CJK text uses bigram/trigram matching.
        """
        query_tokens = _tokenise(query)
        scored: list[tuple[float, Episode]] = []

        for ep in self._episodes:
            score = 0.0
            ep_kw_tokens = {kw.lower() for kw in ep.keywords}
            for qt in query_tokens:
                if qt in ep_kw_tokens:
                    score += 2
            summary_tokens = _tokenise(ep.summary)
            score += len(query_tokens & summary_tokens)
            if score > 0:
                scored.append((score, ep))

        scored.sort(key=lambda x: -x[0])
        return [ep for _, ep in scored[:top_k]]

    def list_all(self) -> list[Episode]:
        return list(self._episodes)


# ---------------------------------------------------------------------------
# Tier 3 — Semantic Memory  (factual knowledge about the user and world)
# ---------------------------------------------------------------------------

@dataclass
class SemanticFact:
    """A single piece of factual knowledge.

    Attributes:
        key:        Short unique identifier, e.g. "user.language".
        value:      The fact itself, e.g. "Python".
        category:   Logical grouping, e.g. "user_profile", "preference", "world".
        confidence: 0.0–1.0; lower values mean the fact may be stale or uncertain.
        updated_at: ISO-8601 timestamp of the last update.
        source:     Where this fact came from, e.g. "user_stated", "inferred".
    """

    key: str
    value: Any
    category: str = "general"
    confidence: float = 1.0
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    source: str = "user_stated"

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "SemanticFact":
        return cls(**data)


class SemanticMemory:
    """Persistent key-value store for structured factual knowledge.

    Unlike EpisodicMemory (which stores *what happened*), SemanticMemory stores
    *what is true* — user preferences, domain facts, world knowledge snippets.

    In hermes-agent this is partly implemented by MEMORY.md (flat text) and
    partly by Honcho's dialectic user-modeling service.

    Cognitive analogy: long-term declarative memory — "Python is a language".
    """

    def __init__(self, filepath: str = ".semantic_memory.json") -> None:
        self.filepath = filepath
        self._facts: dict[str, SemanticFact] = {}
        self._load()

    # --- Persistence ---

    def _load(self) -> None:
        if os.path.exists(self.filepath):
            try:
                with open(self.filepath, "r", encoding="utf-8") as fh:
                    raw: dict = json.load(fh)
                self._facts = {k: SemanticFact.from_dict(v) for k, v in raw.items()}
            except (json.JSONDecodeError, OSError, TypeError):
                self._facts = {}

    def _save(self) -> None:
        with open(self.filepath, "w", encoding="utf-8") as fh:
            json.dump(
                {k: v.to_dict() for k, v in self._facts.items()},
                fh,
                indent=2,
                ensure_ascii=False,
            )

    # --- Write ---

    def remember(
        self,
        key: str,
        value: Any,
        category: str = "general",
        confidence: float = 1.0,
        source: str = "user_stated",
    ) -> None:
        """Store or update a fact."""
        self._facts[key] = SemanticFact(
            key=key,
            value=value,
            category=category,
            confidence=confidence,
            source=source,
        )
        self._save()

    def forget(self, key: str) -> None:
        """Remove a fact by key."""
        self._facts.pop(key, None)
        self._save()

    # --- Read ---

    def recall(self, key: str) -> Optional[Any]:
        """Return the value for *key*, or ``None`` if absent."""
        fact = self._facts.get(key)
        return fact.value if fact else None

    def recall_fact(self, key: str) -> Optional[SemanticFact]:
        """Return the full SemanticFact record for *key*."""
        return self._facts.get(key)

    def by_category(self, category: str) -> list[SemanticFact]:
        """Return all facts in the given *category*, sorted by key."""
        return sorted(
            [f for f in self._facts.values() if f.category == category],
            key=lambda f: f.key,
        )

    def search(self, query: str) -> list[SemanticFact]:
        """Return facts whose key or string-value contains *query* (case-insensitive)."""
        q = query.lower()
        return [
            f for f in self._facts.values()
            if q in f.key.lower() or q in str(f.value).lower()
        ]

    def get_all(self) -> dict[str, SemanticFact]:
        return dict(self._facts)


# ---------------------------------------------------------------------------
# Tier 4 — Procedural Memory  (how-to skills — pointer to ch10)
# ---------------------------------------------------------------------------

class ProceduralMemoryRef:
    """Thin reference layer pointing at ch10's SkillStore.

    In a real agent this class wraps the SkillStore from Chapter 10.
    Here it serves as a documentation placeholder explaining the tier's role.

    Cognitive analogy: muscle memory / procedural knowledge —
    "how to ride a bike" without needing to consciously recall each step.
    """

    INFO = (
        "程序性记忆（技能）由第十章的 SkillStore 实现。"
        "它存储从经验中提炼的可复用步骤性知识（技能），"
        "支持版本化改进和关键词检索。"
        "在多层次记忆体系中，程序性记忆是最具持久性的一层，"
        "因为技能一旦掌握便很少遗忘。"
    )

    @staticmethod
    def description() -> str:
        return ProceduralMemoryRef.INFO


# ---------------------------------------------------------------------------
# Shared tokeniser helper
# ---------------------------------------------------------------------------

def _tokenise(text: str) -> set[str]:
    """Return a set of tokens from *text* (ASCII words + CJK bigrams/trigrams)."""
    tokens: set[str] = set()
    tokens.update(w.lower() for w in re.findall(r"[a-zA-Z]{2,}", text))
    cjk = re.findall(r"[\u4e00-\u9fff]", text)
    for n in (2, 3):
        for i in range(len(cjk) - n + 1):
            tokens.add("".join(cjk[i : i + n]))
    return tokens


# ---------------------------------------------------------------------------
# MultiLevelMemoryManager — unified facade
# ---------------------------------------------------------------------------

class MultiLevelMemoryManager:
    """Facade that coordinates all four memory tiers.

    Usage pattern (mirrors hermes-agent's memory flow):

      manager = MultiLevelMemoryManager(...)

      # Every turn: update working memory
      manager.working.add("user", user_input)
      manager.working.add("assistant", assistant_reply)

      # On session end: compress working memory into an episode
      manager.close_session(session_id="2026-01-01T12:00:00")

      # Remember a fact about the user
      manager.semantic.remember("user.language", "Python", category="user_profile")

      # At the start of a new session: retrieve relevant context
      past_episodes = manager.episodic.search("Python 排序")
      user_lang = manager.semantic.recall("user.language")
    """

    def __init__(
        self,
        *,
        max_working_messages: int = 20,
        episodic_filepath: str = ".episodic_memory.json",
        semantic_filepath: str = ".semantic_memory.json",
    ) -> None:
        self.working = WorkingMemory(max_messages=max_working_messages)
        self.episodic = EpisodicMemory(filepath=episodic_filepath)
        self.semantic = SemanticMemory(filepath=semantic_filepath)
        self.procedural = ProceduralMemoryRef()

    def close_session(
        self,
        session_id: Optional[str] = None,
        started_at: Optional[str] = None,
    ) -> Episode:
        """Compress the current working memory into an episode and persist it.

        In hermes-agent the LLM generates the summary.  Here we use a
        rule-based approach: concatenate role-prefixed snippets.
        """
        sid = session_id or datetime.now().isoformat()
        sat = started_at or datetime.now().isoformat()

        messages = self.working.get_messages()
        summary = self.working.summarise()

        # Extract keywords: all distinct CJK bigrams and ASCII words from content
        all_text = " ".join(m["content"] for m in messages)
        keywords = sorted(_tokenise(all_text))[:12]

        episode = Episode(
            session_id=sid,
            summary=summary,
            keywords=keywords,
            started_at=sat,
            ended_at=datetime.now().isoformat(),
            message_count=len(messages),
        )
        self.episodic.store(episode)
        self.working.clear()
        return episode

    def context_for_new_session(self, query: str = "", top_episodes: int = 3) -> str:
        """Build a context string to inject at the start of a new session.

        Combines:
          - Relevant past episodes (episodic memory)
          - Key user facts (semantic memory / user profile)

        In hermes-agent this context is injected into the system prompt.
        """
        lines: list[str] = []

        # --- Semantic facts (user profile) ---
        user_facts = self.semantic.by_category("user_profile")
        pref_facts = self.semantic.by_category("preference")
        all_facts = user_facts + pref_facts
        if all_facts:
            lines.append("## 关于用户的已知信息")
            for f in all_facts:
                lines.append(f"- {f.key}: {f.value}  [置信度: {f.confidence:.0%}]")

        # --- Relevant past episodes ---
        if query:
            episodes = self.episodic.search(query, top_k=top_episodes)
        else:
            episodes = self.episodic.get_recent(top_episodes)

        if episodes:
            lines.append("\n## 相关历史会话摘要")
            for ep in episodes:
                lines.append(
                    f"- [{ep.session_id[:19]}] ({ep.message_count} 条消息)\n"
                    f"  {ep.summary[:120]}{'…' if len(ep.summary) > 120 else ''}"
                )

        # --- Procedural hint ---
        lines.append(f"\n## 程序性记忆\n- {ProceduralMemoryRef.INFO}")

        return "\n".join(lines) if lines else "(无历史上下文)"


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import pathlib

    base = pathlib.Path(__file__).parent
    episodic_file = str(base / ".demo_episodic.json")
    semantic_file = str(base / ".demo_semantic.json")

    # Clean up previous demo files
    for f in (episodic_file, semantic_file):
        if os.path.exists(f):
            os.remove(f)

    manager = MultiLevelMemoryManager(
        max_working_messages=10,
        episodic_filepath=episodic_file,
        semantic_filepath=semantic_file,
    )

    print("=" * 65)
    print("Chapter 12: Multi-Level Memory Demo")
    print("=" * 65)

    # ------------------------------------------------------------------ #
    # Session 1: user tells the agent about themselves                    #
    # ------------------------------------------------------------------ #
    print("\n\n── Session 1: 用户自我介绍 ──────────────────────────────────")

    manager.working.add("user", "你好！我是 Alice，主要用 Python 做数据分析。")
    manager.working.add("assistant", "你好 Alice！很高兴认识你，请问有什么可以帮你？")
    manager.working.add("user", "我平时喜欢简洁的代码风格，不喜欢过多注释。")
    manager.working.add("assistant", "好的，我会注意保持代码简洁。")

    print(f"  工作记忆中有 {len(manager.working)} 条消息")

    # Store semantic facts extracted from the conversation
    manager.semantic.remember("user.name", "Alice", category="user_profile")
    manager.semantic.remember("user.language", "Python", category="user_profile", confidence=1.0)
    manager.semantic.remember("user.domain", "数据分析", category="user_profile")
    manager.semantic.remember("user.code_style", "简洁，少注释", category="preference")

    print("  → 已存入语义记忆：用户名、语言偏好、领域、代码风格")

    # Close session 1 → compress into episodic memory
    ep1 = manager.close_session(session_id="session-001", started_at="2026-01-01T09:00:00")
    print(f"  → 会话 1 已压缩为情景记忆（{ep1.message_count} 条 → 1 个情景）")
    print(f"    摘要: {ep1.summary[:100]}…")

    # ------------------------------------------------------------------ #
    # Session 2: user asks about sorting                                  #
    # ------------------------------------------------------------------ #
    print("\n\n── Session 2: 用户询问排序问题 ─────────────────────────────")

    manager.working.add("user", "帮我用 Python 对 DataFrame 按照销售额排序。")
    manager.working.add("assistant", "可以用 df.sort_values('销售额', ascending=False)。")
    manager.working.add("user", "能不能返回前 10 名？")
    manager.working.add("assistant", "df.sort_values('销售额', ascending=False).head(10) 即可。")
    manager.working.add("user", "谢谢，再帮我过滤掉空值。")
    manager.working.add("assistant", "df.dropna(subset=['销售额']).sort_values(...).head(10)。")

    print(f"  工作记忆中有 {len(manager.working)} 条消息")

    ep2 = manager.close_session(session_id="session-002", started_at="2026-01-02T14:00:00")
    print(f"  → 会话 2 已压缩为情景记忆（{ep2.message_count} 条 → 1 个情景）")

    # ------------------------------------------------------------------ #
    # Session 3: user returns — agent reconstructs context               #
    # ------------------------------------------------------------------ #
    print("\n\n── Session 3: 新会话开始，重建上下文 ───────────────────────")
    new_query = "DataFrame 排序和过滤"
    context = manager.context_for_new_session(query=new_query)
    print("  注入到新会话 system prompt 的上下文：")
    print()
    for line in context.split("\n"):
        print(f"    {line}")

    # ------------------------------------------------------------------ #
    # Semantic memory inspection                                          #
    # ------------------------------------------------------------------ #
    print("\n\n── 语义记忆检索 ─────────────────────────────────────────────")
    print("  用户档案 (category=user_profile):")
    for fact in manager.semantic.by_category("user_profile"):
        print(f"    {fact.key}: {fact.value}  [来源: {fact.source}]")

    print("\n  偏好 (category=preference):")
    for fact in manager.semantic.by_category("preference"):
        print(f"    {fact.key}: {fact.value}  [置信度: {fact.confidence:.0%}]")

    print("\n  搜索 'Python':")
    for fact in manager.semantic.search("Python"):
        print(f"    {fact.key}: {fact.value}")

    # ------------------------------------------------------------------ #
    # Episodic memory inspection                                          #
    # ------------------------------------------------------------------ #
    print("\n\n── 情景记忆检索 ─────────────────────────────────────────────")
    print(f"  所有情景（共 {len(manager.episodic.list_all())} 个）：")
    for ep in manager.episodic.list_all():
        print(f"    [{ep.session_id}] {ep.message_count} 条  关键词: {ep.keywords[:5]}")

    print(f"\n  搜索「排序」：")
    results = manager.episodic.search("排序", top_k=2)
    for ep in results:
        print(f"    [{ep.session_id}] {ep.summary[:80]}…")

    # ------------------------------------------------------------------ #
    # Procedural memory pointer                                           #
    # ------------------------------------------------------------------ #
    print("\n\n── 程序性记忆 ───────────────────────────────────────────────")
    print(f"  {manager.procedural.description()}")

    # Cleanup
    for f in (episodic_file, semantic_file):
        if os.path.exists(f):
            os.remove(f)

    print("\n\nDemo 完成！")
    print("""
四层记忆体系总结：
  🔵  工作记忆   — 当前对话上下文，会话结束后清空
  🟢  情景记忆   — 历史会话摘要，可按关键词检索
  🟡  语义记忆   — 用户与世界的事实性知识，可按类别查询
  🟠  程序性记忆 — 如何完成任务的技能（见第十章）
""")
